
SELECT 
	CT_ID, BOARD_SEQ, INDEX1, INDEX2, DEPTH, SD_CD, SGG_CD, USER_ID, USER_NAME, USER_EMAIL, USER_PASS, USER_IP, USER_TEL, USER_HOMEPAGE, SUBJECT, CONTENT, REPLIED_YN, SECRET_YN, NOTICE_YN, READ_NUM, UPD_DT, INS_DT, WRT_ID, ETC_1, ETC_2, ETC_3, ETC_4, ETC_5, ETC_6, ETC_7, ETC_8, ETC_9, ETC_10 
FROM   PT_BBS_BOARD ;
                   
