
SELECT 
	SEQ, ORG_NM, SIDO_CODE, PGP_CAF, INS_DT, UPD_DT, WRT_ID, SIGUNGU_CODE, PGP_PMS, NBS_4_CAF, NBS_4_PMS, NBS_6_CAF, NBS_6_PMS, NBS_7_CAF, NBS_7_PMS, NBS_8_CAF, NBS_9_PMS, NBS_9_CAF, NBS_8_PMS, TBS_TECOM_CAF, TBS_TECOM_PMS, TBS_EXCH_CAF, TBS_EXCH_PMS 
FROM   PT_C_RES_COMM_LIMIT ;
                   
