
SELECT 
	SEQ, ORG_NM, SIDO_CODE, SKT_QTT, SKT_AOM, INS_DT, UPD_DT, WRT_ID, SIGUNGU_CODE, KTF_QTT, KTF_AOM, LGT_QTT, LGT_AOM, QTT_010, AOM_010, WATT 
FROM   PT_C_RES_MOBILE_PHONE ;
                   
