
SELECT 
	USER_ID, USER_NAME, USER_PASSWD, USER_NAT_NUM1, USER_NAT_NUM2, USER_EMAIL, USER_ZIPCODE, USER_ADDR, USER_ADDR_ETC, USER_TEL, USER_MOBILE, USER_SEX, INP_SITE, SC_CD, SGG_CD, CAPITAL, BIGO, SMS_YN, NEWS_YN, USE_CODE, INS_DT, UPD_DT 
FROM   PT_HOM_USER ;
                   
