
SELECT 
	TMP_WRT_NUM, WRT_NUM, BUSISUSP_START_DT, BUSISUSP_END_DT, OPIN_COLL_DT, OPIN_COLL_CONT, INS_DT, UPD_DT, WRT_ID, LIS_END_DATE, BEFORE_DISPO, OPINI_SUBMIT_DATE, OPINI_SUBMIT, DECISION_DATE, DISPO_PERIOD 
FROM   PT_M_SUSPENSION ;
                   
