
SELECT 
	SEQ, NOTE_CLASS_CODE, SEND_DT, S_PER, PROC_LIM, RECV_YN, REMARK, INS_DT, UPD_DT, WRT_ID, TMP_WRT_NUM, WRT_NUM, RECV_LOC, NOTE_METHOD_CLASS, GUBUN 
FROM   PT_M_BEF_REPORT ;
                   
