
SELECT 
	TMP_WRT_NUM, WRT_NUM, OPIN_COLL_DT, OPIN_COLL_CONT, INS_DT, UPD_DT, WRT_ID, NEFI, PAY_LIM, PAY_DT, PAY_YN, REMARK, DESION_DATE, LIS_END_DATE, OPINI_SUBMIT, BEFORE_DISPO, OPINI_SUBMIT_DATE 
FROM   PT_M_NEGLIGENCE ;
                   
