
SELECT 
	SEQ, RECV_NAME, RECV_PART_SIDO, RECV_PART_SIGUNGU, RECV_POS, CONSULT_NAME, CONSULT_PART_SIDO, CONSULT_PART_SIGUNGU, CONSULT_POS, RECV_DT, RECV_METHOD, DEMAND_CONTENTS, REMARK, PROC_OUT, PROC_DT, PROC_TIME, RECV_AREA, CONSULT_AREA 
FROM   PT_MODIFY_REQ ;
                   
