
SELECT 
	TMP_WRT_NUM, WRT_NUM, OPIN_COLL_DT, OPIN_COLL_CONT, INS_DT, UPD_DT, WRT_ID, NEFI, DECISION_DATE, LIS_END_DATE, OPINI_SUBMIT_DATE, OPINI_SUBMIT, BEFORE_DISPO, BUSISUSP_START_DT, BUSISUSP_END_DT, DISPO_PERIOD, PAYLIM 
FROM   PT_M_SUSNEG ;
                   
