
SELECT 
	TMP_WRT_NUM, WRT_NUM, WRT_DT, REGR, VIOL_CONT_CODE, VIOL_DT, D_PER_CODE, DISPO_CONT, DISPO_CAUSE, DISPO_DT, MOT_STE, INS_DT, UPD_DT, WRT_ID, SIDO_CODE, REMARK, LEG_BAS, SND_STE, SND_DT, HOME_NOTE, NOTE_GUID_DT, OFFI_REPORT_DT, ASSO_GUILD_DT, RECV_NUM, DISPO_CONT2, BUSISUSP_START_DT, BUSISUSP_END_DT, DOC_CODE, PUNISHMENT_AGENCY, DISPO_CONT_NM, AT_RECV_NUM, MAST_PROC 
FROM   PT_M_MASTER ;
                   
