
SELECT 
	SEQ, NOTE_CLASS_CODE, SEND_DT, S_PER, RECV_YN, REMARK, INS_DT, UPD_DT, WRT_ID, TMP_WRT_NUM, WRT_NUM, NOTE_NAME, NOTE_METHOD_CLASS, RECV_LOC, GUBUN 
FROM   PT_M_AUDI_BEF_REPORT ;
                   
