
SELECT 
	RECV_NUM, SIDO_CODE, COI_WRT_NUM, RECV_DT, OFFI_PART, OFFI_PART_REBO_WRT_NUM, NAME, WRT_NUM, REP, TEL_NUM, FAX_NUM, OFF_ADDR, WRT_ID, UPD_DT, INS_DT, MOT_STE, DEFI_STE, COI, WRTBOOK, APPL_CAUSE, TMP_WRT_NUM, DOC_CODE, SND_STE, SND_DT 
FROM   PT_R_RE_DERIVERY_STATEMENT ;
                   
