
SELECT 
	RECV_NUM, SIDO_CODE, WRT_ID, UPD_DT, INS_DT, ASC_TMP_WRT_NUM, HANDED_TMP_WRT_NUM, MOT_STE, ESTA_TMP_WRT_NUM, ESTA_ADDR_TEL_NUM, ESTA_NAME, ESTA_REP_NM_KOR, ESTA_REP_NM_HAN, ESTA_MANA_NUM, ESTA_ADDR_ADDR, ESTA_ADDR_POST_NUM, ESTA_ADDR_DETAIL_ADDR, ESTA_WRT_NUM, DEFI_STE, PROC_LIM, PROC_TIME, RECV_DT, RECV_TIME, BUSS_YMD, FOREIGN, REGIST_YMD 
FROM   PT_R_UNION_STATEMENT ;
                   
