
create table PT_R_MOT_STE(
    CHGBRE_SEQ NUMBER(4) NOT NULL , /* */
    TMP_WRT_NUM VARCHAR2(12) NOT NULL , /* */
    DETAILWORK1 VARCHAR2(1)  , /* */
    DETAILWORK2 VARCHAR2(1)  , /* */
    DETAILWORK3 VARCHAR2(1)  , /* */
    DETAILWORK4 VARCHAR2(1)  , /* */
    DETAILWORK5 VARCHAR2(1)  , /* */
    DETAILWORK6 VARCHAR2(1)  , /* */
    DETAILWORK7 VARCHAR2(1)  , /* */
    DETAILWORK8 VARCHAR2(1)  , /* */
    DETAILWORK9 VARCHAR2(1)  , /* */
    DETAILWORK10 VARCHAR2(1)  , /* */
    DETAILWORK11 VARCHAR2(1)  , /* */
    DETAILWORK12 VARCHAR2(1)  , /* */
    DETAILWORK13 VARCHAR2(1)  , /* */
    DETAILWORK14 VARCHAR2(1)  , /* */
    DETAILWORK15 VARCHAR2(1)  , /* */
    DETAILWORK16 VARCHAR2(1)  , /* */
    RECV_NUM VARCHAR2(20)  , /* */
    MOT_PROC VARCHAR2(2)  , /* */
    SIDO_CODE VARCHAR2(4)  , /* */
    PRIMARY KEY(CHGBRE_SEQ,TMP_WRT_NUM)
   );
