
SELECT 
	RECV_NUM, SIDO_CODE, RECV_DT, RECV_TIME, PROC_LIM, OFFI_PART, OFFI_PART_REBO_WRT_NUM, NAME, MANA_NUM, COM_NUM, REP_NM_KOR, REP_NM_HAN, ADDR_POST_NUM, ADDR_DETAIL_ADDR, ADDR_TEL_NUM, ADDR_FAX_NUM, DEFI_STE, WRT_ID, UPD_DT, INS_DT, ADDR_ADDR, PROC_TIME, REP_MOBILE, REP_MOBILE2, REP_MOBILE3, ADDR_TEL_NUM2, ADDR_TEL_NUM3, ADDR_FAX_NUM2, ADDR_FAX_NUM3, ADDR_TEL_NUM1, ADDR_FAX_NUM1, REP_MOBILE1, REP_SSN1, REP_SSN2, GUBUN, COI_WRT_NUM, MOT_STE, DOC_CODE, COMMANA_CLASS, OFFICE_AREA, DIAG_ORG_CODE, DIAG_NM_NM, COMPANY_DIAG_BAS_DT, PAY_CAP, DIAG_NM_WRT_NUM, COMPANY_DIAG_ISSUE_DT, REA_CAP, TUP_CLASS_CODE, TUP_AOM, OFFICE_USE_NAME, OFFICE_OWN_CLASS, LICTAX, HOSCRE, MEMO_CONT, TMP_WRT_NUM, WRT_DT, BUSS_YMD, FOREIGN_YN, REGIST_YMD, STA_CHG_CLASS_CODE, CHG_DT, EXT_CHG_CLASS_CODE 
FROM   PT_R_REGIST_STATEMENT ;
                   
