
SELECT 
	CHGBRE_SEQ, TMP_WRT_NUM, DETAILWORK1, DETAILWORK2, DETAILWORK3, DETAILWORK4, DETAILWORK5, DETAILWORK6, DETAILWORK7, DETAILWORK8, DETAILWORK9, DETAILWORK10, DETAILWORK11, DETAILWORK12, DETAILWORK13, DETAILWORK14, DETAILWORK15, DETAILWORK16, RECV_NUM, MOT_PROC, SIDO_CODE 
FROM   PT_R_MOT_STE ;
                   
