
SELECT 
	SEQ, TMP_WRT_NUM, RECV_NUM, ENGINEER_NM, ENGINEER_SSN1, ENGINEER_SSN2, EMPL_YMD, RET_YMD, REMARK, WRT_ID, UPD_DT, INS_DT, TMP_FIELD, CARE_BOOK_VAL_START_DT, CARE_BOOK_VAL_END_DT, ISSUE_DT, CARE_BOOK_ISSUE_NUM, CARE_BOOK_VAL_START_DT1, CARE_BOOK_VAL_START_DT2, ENG_PROC, ENG_TARGET 
FROM   PT_R_ENGINEER_CHANGE_TEMP ;
                   
