
SELECT 
	RECV_NUM, SIDO_CODE, RECV_DT, RECV_TIME, PROC_LIM, OFFI_PART, OFFI_PART_REBO_WRT_NUM, COI_WRT_NUM, DEFI_STE, WRT_ID, UPD_DT, INS_DT, NAME, REP_NM_KOR, ADDR_ADDR, WRT_DT, PROC_TIME, ADDR_DETAIL_ADDR, ADDR_POST_NUM, TMP_WRT_NUM, CHGBRE_SEQ, MEMO_CONT, COMMANA_CLASS, MANA_NUM, REP_SSN1, REP_SSN2, REP_NM_HAN, REP_TEL_NUM, ADDR_TEL_NUM, ADDR_FAX_NUM, EMAIL_ADDR, OFFICE_AREA, OFFICE_USE_CODE, COMPANY_DIAG_CLASS_CODE, COMPANY_DIAG_BAS_DT, COMPANY_DIAG_ISSUE_DT, DIAG_NM_NM, DIAG_NM_WRT_NUM, DIAG_ORG_CODE, PAY_CAP, REA_CAP, TUP_CLASS_CODE, TUP_AOM, C_COM_DT, C_COM_CAUSE_CODE, COM_COV_DT, BAS_STA_DT, OFFICE_OWN_CLASS, STA_CHG_CLASS_CODE, CHG_DT, MOT_STE, REP_MOBILE, HOSCRE, LICTAX, SND_DT, SND_STE, COM_NUM, COMPANY_DIAG_BAS_DT2, EXT_CHG_CLASS_CODE, DOC_CODE, GUBUN, OFFICE_USE_NAME, BUSS_YMD, FOREIGN_YN, REGIST_YMD, UNION_INVEST_NUM, MIDAL_YN 
FROM   PT_R_BASIC_STATEMENT ;
                   
