
create table PT_R_ENGINEER_CHANGE_TEMP(
    SEQ NUMBER(4) NOT NULL , /* */
    TMP_WRT_NUM VARCHAR2(12) NOT NULL , /* */
    RECV_NUM VARCHAR2(12) NOT NULL , /* */
    ENGINEER_NM VARCHAR2(20)  , /* */
    ENGINEER_SSN1 VARCHAR2(18)  , /* */
    ENGINEER_SSN2 VARCHAR2(21)  , /* */
    EMPL_YMD VARCHAR2(8)  , /* */
    RET_YMD VARCHAR2(8)  , /* */
    REMARK VARCHAR2(256)  , /* */
    WRT_ID VARCHAR2(16)  , /* */
    UPD_DT VARCHAR2(24)  , /* */
    INS_DT VARCHAR2(24)  , /* */
    TMP_FIELD VARCHAR2(20)  , /* */
    CARE_BOOK_VAL_START_DT VARCHAR2(24)  , /* */
    CARE_BOOK_VAL_END_DT VARCHAR2(24)  , /* */
    ISSUE_DT VARCHAR2(24)  , /* */
    CARE_BOOK_ISSUE_NUM VARCHAR2(30)  , /* */
    CARE_BOOK_VAL_START_DT1 VARCHAR2(30)  , /* */
    CARE_BOOK_VAL_START_DT2 VARCHAR2(30)  , /* */
    ENG_PROC VARCHAR2(2)  , /* */
    ENG_TARGET VARCHAR2(2)  , /* */
    PRIMARY KEY(RECV_NUM,SEQ,TMP_WRT_NUM)
   );
