
create table PT_R_COMPANY_DIAGNOSTIC(
    CHGBRE_SEQ VARCHAR2(4) NOT NULL , /* */
    TMP_WRT_NUM VARCHAR2(12) NOT NULL , /* */
    DIAG_ORG_CODE VARCHAR2(6)  , /* */
    PAY_CAP VARCHAR2(15)  , /* */
    REA_CAP VARCHAR2(15)  , /* */
    TUP_AOM VARCHAR2(15)  , /* */
    TUP_CLASS_CODE VARCHAR2(6)  , /* */
    COMPANY_DIAG_CLASS_CODE VARCHAR2(6)  , /* */
    COMPANY_DIAG_BASDT VARCHAR2(8)  , /* */
    COMPANY_DIAG_ISSUEDT VARCHAR2(8)  , /* */
    DIAG_NM_NM VARCHAR2(20)  , /* */
    DIAG_NM_WRT_NUM VARCHAR2(12)  , /* */
    WRT_ID VARCHAR2(16)  , /* */
    UPD_DT VARCHAR2(24)  , /* */
    INS_DT VARCHAR2(24)  , /* */
    PRIMARY KEY(CHGBRE_SEQ,TMP_WRT_NUM)
   );
