
SELECT 
	SD_CODE, SEQ, SGG_CODE, GUBUN, WRT_ID, UDP_DT, NAME_HANJA, INS_DT, SSN1, NOTE, ADDR, FAMILY_HEAD, SSN2, FAMILY_HEAD_RELATION, NAME_KOR, ORIGIN, TMP_REG_NUM, ENTER_DATE, RETIRE_DATE, REFER_YN 
FROM   PT_R_REFER ;
                   
