
SELECT 
	REC_NUM, REG_NUM, SC_CODE, SGG_CODE, REC_DATE, PRO_PERIOD, PRO_DUTY, PRO_REC_NUM, COMPANY_NM, APPLICANT, TEL, FAX, REMEMBRANCER, SSN1, SSN2, POST_CODE, ADDR, ADDR_ETC, PUBLIC_WORK, REP_NUM, REC_DUTY, REC_WRITE, REC_INS_DT, WRT_ID, UDP_DT, INS_DT, NOTE 
FROM   PT_SAMPLE ;
                   
