
SELECT 
	USER_CODE, USER_NAME, USER_ID, USER_PASSWD, USER_EMAIL, USER_TEL, USER_MOBILE, USER_NAT_NUM, POST, EMAIL, CAPITAL, USE_YN, REG_DATE, MOD_DATE, LAST_CONN, ORGANIZATION, POSITION, STAFF_SYSTEM, STAFF_LEVEL, USER_AUTH, USER_LEVEL 
FROM   PT_USER ;
                   
