
create table PT_UB_CONDEFICIT(
    DEFI_SEQ NUMBER(4) NOT NULL , /* */
    DEFI_CODE VARCHAR2(6)  , /* */
    DEFI_OUT VARCHAR2(1)  , /* */
    WRT_ID VARCHAR2(16)  , /* */
    UPD_DT VARCHAR2(24)  , /* */
    INS_DT VARCHAR2(24)  , /* */
    RECV_NUM VARCHAR2(12) NOT NULL , /* */
    SIDO_CODE VARCHAR2(20) NOT NULL , /* */
    SIGUNGU_CODE VARCHAR2(4) NOT NULL , /* */
    PRIMARY KEY(DEFI_SEQ,RECV_NUM,SIDO_CODE,SIGUNGU_CODE)
   );
