
SELECT 
	RECV_NUM, SIDO_CODE, SIGUNGU_CODE, CIV_RECV_NUM, TYPE_PROC_NO_CA, TYPE_PROC_NM_CA, FREQUENCY_SCOPE_CA, WIRE_TYPE_CA, TYPE_PROC_NO_MA, TYPE_PROC_NM_MA, FREQUENCY_SCOPE_MA, WIRE_TYPE_MA, TYPE_PROC_NO_SMA, TYPE_PROC_NM_SMA, FREQUENCY_SCOPE_SMA, WIRE_TYPE_SMA, INS_DT, UPD_DT 
FROM   PT_UB_EQUIPMENT ;
                   
