
SELECT 
	RECV_NUM, SUV_NAME, SUV_STANUM, SUV_NM, SUV_TELNUM, SUV_POSTNUM, SUV_ADDR, SUV_DETAILADDR, SIWORK_NAME, SIWORK_REP, COI_WRT_NUM, SIWORK_POSTNUM, SIWORK_ADDR, SIWORK_DETAILADDR, SPOTNM, SPOT_POSTNUM, SPOT_ADDR, SPOT_DETAILADDR, WORK_ITEM, USE, STRU_AREA, AREA, SW_DT, EW_DT, WRT_ID, INS_DT, UPD_DT, SIDO_CODE, SIGUNGU_CODE, SUV_MOBILE, SIWORK_TELNUM, SIWORK_MOBILE, DOC_YN, PROC_LIM, ORPE_NM, WORK_ITEM_ETC, UPD_DT_OLD, BACKUP_TRANS_DT, CIV_RECV_NUM, USE_ETC, RECV_NUM, SUV_NAME, SUV_STANUM, SUV_NM, SUV_TELNUM, SUV_POSTNUM, SUV_ADDR, SUV_DETAILADDR, SIWORK_NAME, SIWORK_REP, COI_WRT_NUM, SIWORK_POSTNUM, SIWORK_ADDR, SIWORK_DETAILADDR, SPOTNM, SPOT_POSTNUM, SPOT_ADDR, SPOT_DETAILADDR, WORK_ITEM, USE, STRU_AREA, AREA, SW_DT, EW_DT, WRT_ID, INS_DT, UPD_DT, SIDO_CODE, SIGUNGU_CODE, SUV_MOBILE, SIWORK_TELNUM, SIWORK_MOBILE, DOC_YN, PROC_LIM, ORPE_NM, WORK_ITEM_ETC, UPD_DT_OLD, BACKUP_TRANS_DT, CIV_RECV_NUM 
FROM   PT_UB_SUVSPOT ;
                   
