
create table PT_UB_SUVSPOT(
    RECV_NUM VARCHAR2(30) NOT NULL , /* */
    SUV_NAME VARCHAR2(100)  , /* */
    SUV_STANUM VARCHAR2(24)  , /* */
    SUV_NM VARCHAR2(26)  , /* */
    SUV_TELNUM VARCHAR2(24)  , /* */
    SUV_POSTNUM VARCHAR2(6)  , /* */
    SUV_ADDR VARCHAR2(64)  , /* */
    SUV_DETAILADDR VARCHAR2(128)  , /* */
    SIWORK_NAME VARCHAR2(100)  , /* */
    SIWORK_REP VARCHAR2(25)  , /* */
    COI_WRT_NUM VARCHAR2(26)  , /* */
    SIWORK_POSTNUM VARCHAR2(6)  , /* */
    SIWORK_ADDR VARCHAR2(64)  , /* */
    SIWORK_DETAILADDR VARCHAR2(128)  , /* */
    SPOTNM VARCHAR2(125)  , /* */
    SPOT_POSTNUM VARCHAR2(6)  , /* */
    SPOT_ADDR VARCHAR2(64)  , /* */
    SPOT_DETAILADDR VARCHAR2(128)  , /* */
    WORK_ITEM VARCHAR2(128)  , /* */
    USE VARCHAR2(128)  , /* */
    STRU_AREA VARCHAR2(250)  , /* */
    AREA VARCHAR2(12)  , /* */
    SW_DT VARCHAR2(24)  , /* */
    EW_DT VARCHAR2(24)  , /* */
    WRT_ID VARCHAR2(16)  , /* */
    INS_DT VARCHAR2(24)  , /* */
    UPD_DT VARCHAR2(24)  , /* */
    SIDO_CODE VARCHAR2(4) NOT NULL , /* */
    SIGUNGU_CODE VARCHAR2(6) NOT NULL , /* */
    SUV_MOBILE VARCHAR2(24)  , /* */
    SIWORK_TELNUM VARCHAR2(24)  , /* */
    SIWORK_MOBILE VARCHAR2(24)  , /* */
    DOC_YN VARCHAR2(5)  , /* */
    PROC_LIM VARCHAR2(24)  , /* */
    ORPE_NM VARCHAR2(50)  , /* */
    WORK_ITEM_ETC VARCHAR2(128)  , /* */
    UPD_DT_OLD VARCHAR2(24)  , /* */
    BACKUP_TRANS_DT VARCHAR2(24)  , /* */
    CIV_RECV_NUM VARCHAR2(50)  , /* */
    USE_ETC VARCHAR2(256)  , /* */
    RECV_NUM VARCHAR2(30) NOT NULL , /* */
    SUV_NAME VARCHAR2(100)  , /* */
    SUV_STANUM VARCHAR2(24)  , /* */
    SUV_NM VARCHAR2(26)  , /* */
    SUV_TELNUM VARCHAR2(24)  , /* */
    SUV_POSTNUM VARCHAR2(6)  , /* */
    SUV_ADDR VARCHAR2(64)  , /* */
    SUV_DETAILADDR VARCHAR2(128)  , /* */
    SIWORK_NAME VARCHAR2(100)  , /* */
    SIWORK_REP VARCHAR2(25)  , /* */
    COI_WRT_NUM VARCHAR2(26)  , /* */
    SIWORK_POSTNUM VARCHAR2(6)  , /* */
    SIWORK_ADDR VARCHAR2(64)  , /* */
    SIWORK_DETAILADDR VARCHAR2(128)  , /* */
    SPOTNM VARCHAR2(125)  , /* */
    SPOT_POSTNUM VARCHAR2(6)  , /* */
    SPOT_ADDR VARCHAR2(64)  , /* */
    SPOT_DETAILADDR VARCHAR2(128)  , /* */
    WORK_ITEM VARCHAR2(128)  , /* */
    USE VARCHAR2(128)  , /* */
    STRU_AREA VARCHAR2(250)  , /* */
    AREA VARCHAR2(12)  , /* */
    SW_DT VARCHAR2(24)  , /* */
    EW_DT VARCHAR2(24)  , /* */
    WRT_ID VARCHAR2(16)  , /* */
    INS_DT VARCHAR2(24)  , /* */
    UPD_DT VARCHAR2(24)  , /* */
    SIDO_CODE VARCHAR2(4) NOT NULL , /* */
    SIGUNGU_CODE VARCHAR2(6) NOT NULL , /* */
    SUV_MOBILE VARCHAR2(24)  , /* */
    SIWORK_TELNUM VARCHAR2(24)  , /* */
    SIWORK_MOBILE VARCHAR2(24)  , /* */
    DOC_YN VARCHAR2(5)  , /* */
    PROC_LIM VARCHAR2(24)  , /* */
    ORPE_NM VARCHAR2(50)  , /* */
    WORK_ITEM_ETC VARCHAR2(128)  , /* */
    UPD_DT_OLD VARCHAR2(24)  , /* */
    BACKUP_TRANS_DT VARCHAR2(24)  , /* */
    CIV_RECV_NUM VARCHAR2(50)  , /* */
    PRIMARY KEY(RECV_NUM,RECV_NUM,SIDO_CODE,SIDO_CODE,SIGUNGU_CODE,SIGUNGU_CODE)
   );
