
create table PT_XML(
    USERID VARCHAR2(50) NOT NULL , /* */
    FORMID VARCHAR2(50) NOT NULL , /* */
    SAMPLENAME VARCHAR2(50) NOT NULL , /* */
    XML VARCHAR2(4000)  , /* */
    DSNAME VARCHAR2(50) NOT NULL , /* */
    PRIMARY KEY(DSNAME,FORMID,SAMPLENAME,USERID)
   );
