
SELECT 
	CT_ID, BOARD_NAME, BOARD_URL, BOARD_CATEGORY, BOARD_TYPE, BOARD_SKIN, BOARD_WIDTH, BOARD_ALIGN, BBS_OWNER, BBS_GROUP, BBS_DEPTH, CUT_TITLE, ROWPERPAGE, NEW_DAY, TITLE_WRT_YN, TITLE_DATE_YN, TITLE_HIT_YN, TITLE_IP_YN, HEADER_HTML, MAIN_HTML, BOTTOM_HTML, LIST_LEVEL, READ_LEVEL, WRITE_LEVEL, ATTACH_YN, FILE_SIZE, ATT_NUM, REPLY_YN, ONE_LINE_YN, SECRET_YN, USE_YN, DIV_USE_YN, SD_DIV_YN, SGG_DIV_YN, VIEW_LIST_YN, ONE_ONE_YN, FILTER, TABLE_ONE_YN, SUBJ_1, SUBJ_2, SUBJ_3, SUBJ_4, SUBJ_5, SUBJ_6, SUBJ_7, SUBJ_8, SUBJ_9, SUBJ_10, UPD_DT, WRT_ID, INS_DT, PUBLIC_DIV_YN 
FROM   PT_BBS_COM_CT ;
                   
