
SELECT 
	SEQ, ORG_NM, SIDO_CODE, IPP_ITEM_NM, IPM_QTT, IPP_INSTAL_DT, IPP_ESTAB_AOM, INS_DT, UPD_DT, WRT_ID, IPP_PDT, SIGUNGU_CODE, IPM_PDT, IPM_ITEM_NM, IPM_ESTAB_AOM 
FROM   PT_C_RES_IPT ;
                   
