
SELECT 
	SEQ, ORG_NM, SIDO_CODE, ITEM_NM, INLINE_NUM, OUTLINE_CH_NUM, OUTLINE_E1_NUM, INSTAL_DT, ESTAB_AOM, REMARK, INS_DT, UPD_DT, WRT_ID, SIGUNGU_CODE 
FROM   PT_C_RES_SWIT ;
                   
