
SELECT 
	WARN_CONT, WARN_DT, WRT_ID, INS_DT, UPD_DT, TMP_WRT_NUM, WRT_NUM, OPIN_COLL_CONT, DECISION_DATE, LIS_END_DATE, OPINI_SUBMIT, OPINI_SUBMIT_DATE, BEFORE_DISPO 
FROM   PT_M_WARNING ;
                   
