
SELECT 
	OFFI_ID, NM, TEL, SIDO_CODE, SIGUNGU_CODE, PART, POS, GROUP_CODE, WRT_ID, INS_DT, UPD_DT, PASS, HOME_GROUP, MOBILE, E_MAIL, OFFSEAL, TEL1, TEL2, TEL3, MOBILE1, MOBILE2, MOBILE3, PHOTO, FAX1, FAX2, FAX3, FAX 
FROM   PT_MI_USER_BASIC ;
                   
