
SELECT 
	TMP_WRT_NUM, WRT_NUM, AUDI_SUBJ, AUDI_SUPINT_PART, AUDI_SUPINT_POS, AUDI_SUPINT_NM, AUDI_ATTEND_PERSON_NM, AUDI_ATTEND_PERSON_PART, AUDI_PER_ATTE_YN, AUDI_PER_NATTE_CAUSE, AUDI_OPN_YN, AUDI_NOPN_CAUSE, PER_STAT_CONT, PER_PRES_EVID, EVID_INV_EVID, ETC, INS_DT, UPD_DT, WRT_ID, EVID_INV_POIN, AUDI_ATTEND_PERSON_POS, AUDI_EXEC_DT, AUDI_EXEC_TIME, AUDI_EXEC_LOC 
FROM   PT_M_AUDI_DICTION ;
                   
