
SELECT 
	TMP_WRT_NUM, WRT_NUM, AUDI_SUBJ, ADMI_DISPO_CAUSE, ADMI_DISPO_CONT, AUDI_SUPINT_PART, AUDI_SUPINT_POS, AUDI_SUPINT_NM, AUDI_PER_NM, AUDI_PER_ADDR, LEG_BAS, AUDI_EXEC_ORG, AUDI_EXEC_PART, AUDI_EXEC_ADDR, AUDI_EXEC_DETAILADDR, AUDI_EXEC_DT, AUDI_EXEC_TIME, INS_DT, UPD_DT, WRT_ID 
FROM   PT_M_AUDI_REPORT ;
                   
