
SELECT 
	M_SEQ, COI_WRT_NUM, TMP_WRT_NUM, DISPO_CLASS, VIOL_DT, DISPO_CAUSE, NOTE_DT, NOTE_RECV_YN, NOTE_OPIN_PRES_LIM_DT, DEL_NOTE_DT, DEL_OPIN_PRES_LIM_DT, DISPO_CONT, DISPO_DT, BUSISUSP_START_DT, BUSISUSP_END_DT, REMARK, RECV_DT, MOT_STE, DOC_CODE, INS_DT, UPD_DT, WRT_ID, REGSTD_START_DT, REGSTD_END_DT, FINE, PAY_NOTI_DT, PAY_TERM, PAY_DT, DEL_RECV_YN, WRT_NUM, SIDO_CODE, SND_STE, SND_DT, PUNISHMENT_AGENCY, DISPO_CONT_NM, AUDI_EXEC_ADDR, AUDI_EXEC_DT, AUDI_EXEC_START_TIME, AUDI_EXEC_END_TIME, AUDI_SUPINT_NM, AUDI_SUPINT_POS 
FROM   PT_M_MGR ;
                   
