
create table PT_M_AUDI_DICTION(
    TMP_WRT_NUM VARCHAR2(12) NOT NULL , /* */
    WRT_NUM VARCHAR2(12) NOT NULL , /* */
    AUDI_SUBJ VARCHAR2(50)  , /* */
    AUDI_SUPINT_PART VARCHAR2(50)  , /* */
    AUDI_SUPINT_POS VARCHAR2(50)  , /* */
    AUDI_SUPINT_NM VARCHAR2(20)  , /* */
    AUDI_ATTEND_PERSON_NM VARCHAR2(20)  , /* */
    AUDI_ATTEND_PERSON_PART VARCHAR2(50)  , /* */
    AUDI_PER_ATTE_YN VARCHAR2(1)  , /* */
    AUDI_PER_NATTE_CAUSE VARCHAR2(512)  , /* */
    AUDI_OPN_YN VARCHAR2(1)  , /* */
    AUDI_NOPN_CAUSE VARCHAR2(512)  , /* */
    PER_STAT_CONT VARCHAR2(1024)  , /* */
    PER_PRES_EVID VARCHAR2(512)  , /* */
    EVID_INV_EVID VARCHAR2(512)  , /* */
    ETC VARCHAR2(256)  , /* */
    INS_DT VARCHAR2(24)  , /* */
    UPD_DT VARCHAR2(24)  , /* */
    WRT_ID VARCHAR2(16)  , /* */
    EVID_INV_POIN VARCHAR2(1024)  , /* */
    AUDI_ATTEND_PERSON_POS VARCHAR2(50)  , /* */
    AUDI_EXEC_DT VARCHAR2(8)  , /* */
    AUDI_EXEC_TIME VARCHAR2(4)  , /* */
    AUDI_EXEC_LOC VARCHAR2(256)  , /* */
    PRIMARY KEY(TMP_WRT_NUM,WRT_NUM)
   );
