
create table PT_M_AUDI_REPORT(
    TMP_WRT_NUM VARCHAR2(12) NOT NULL , /* */
    WRT_NUM VARCHAR2(12) NOT NULL , /* */
    AUDI_SUBJ VARCHAR2(50)  , /* */
    ADMI_DISPO_CAUSE VARCHAR2(1024)  , /* */
    ADMI_DISPO_CONT VARCHAR2(6)  , /* */
    AUDI_SUPINT_PART VARCHAR2(50)  , /* */
    AUDI_SUPINT_POS VARCHAR2(50)  , /* */
    AUDI_SUPINT_NM VARCHAR2(20)  , /* */
    AUDI_PER_NM VARCHAR2(60)  , /* */
    AUDI_PER_ADDR VARCHAR2(200)  , /* */
    LEG_BAS VARCHAR2(6)  , /* */
    AUDI_EXEC_ORG VARCHAR2(40)  , /* */
    AUDI_EXEC_PART VARCHAR2(50)  , /* */
    AUDI_EXEC_ADDR VARCHAR2(100)  , /* */
    AUDI_EXEC_DETAILADDR VARCHAR2(100)  , /* */
    AUDI_EXEC_DT VARCHAR2(8)  , /* */
    AUDI_EXEC_TIME VARCHAR2(4)  , /* */
    INS_DT VARCHAR2(24)  , /* */
    UPD_DT VARCHAR2(24)  , /* */
    WRT_ID VARCHAR2(16)  , /* */
    PRIMARY KEY(TMP_WRT_NUM,WRT_NUM)
   );
