
SELECT 
	TMP_WRT_NUM, WRT_NUM, CORRECT_ORDER_CONT, CORRECT_ORDER_START_DT, CORRECT_ORDER_END_DT, INS_DT, UPD_DT, WRT_ID, DECISION_DATE, LIS_END_DATE, BEFORE_DISPO, OPINI_SUBMIT, OPINI_SUBMIT_DATE 
FROM   PT_M_CORRECT ;
                   
