
create table PT_R_ASSI_TRANS_STATEMENT(
    RECV_NUM VARCHAR2(12) NOT NULL , /* */
    SIDO_CODE VARCHAR2(4) NOT NULL , /* */
    COI_WRT_NUM VARCHAR2(6)  , /* */
    MOT_STE VARCHAR2(6)  , /* */
    DEFI_STE VARCHAR2(1)  , /* */
    RECV_DT VARCHAR2(8)  , /* */
    RECV_TIME VARCHAR2(6)  , /* */
    PROC_LIM VARCHAR2(8)  , /* */
    PROC_TIME VARCHAR2(4)  , /* */
    CHG_DT VARCHAR2(24)  , /* */
    COMMANA_CLASS VARCHAR2(1)  , /* */
    MANA_NUM VARCHAR2(18)  , /* */
    NAME VARCHAR2(50)  , /* */
    REP_SSN1 VARCHAR2(18)  , /* */
    REP_SSN2 VARCHAR2(21)  , /* */
    REP_NM_KOR VARCHAR2(20)  , /* */
    REP_NM_HAN VARCHAR2(20)  , /* */
    REP_TEL_NUM VARCHAR2(17)  , /* */
    ADDR_POST_NUM VARCHAR2(6)  , /* */
    ADDR_ADDR VARCHAR2(120)  , /* */
    ADDR_DETAIL_ADDR VARCHAR2(120)  , /* */
    ADDR_TEL_NUM VARCHAR2(17)  , /* */
    ADDR_FAX_NUM VARCHAR2(17)  , /* */
    EMAIL_ADDR VARCHAR2(30)  , /* */
    OFFICE_AREA VARCHAR2(10)  , /* */
    OFFICE_USE_CODE VARCHAR2(6)  , /* */
    COMPANY_DIAG_CLASS_CODE VARCHAR2(6)  , /* */
    COMPANY_DIAG_BAS_DT VARCHAR2(8)  , /* */
    COMPANY_DIAG_ISSUE_DT VARCHAR2(8)  , /* */
    DIAG_ORG_CODE VARCHAR2(6)  , /* */
    DIAG_NM_NM VARCHAR2(50)  , /* */
    DIAG_NM_WRT_NUM VARCHAR2(50)  , /* */
    PAY_CAP VARCHAR2(15)  , /* */
    REA_CAP VARCHAR2(15)  , /* */
    TUP_AOM VARCHAR2(15)  , /* */
    TUP_CLASS_CODE VARCHAR2(6)  , /* */
    COM_COV_DT VARCHAR2(8)  , /* */
    BAS_STA_DT VARCHAR2(8)  , /* */
    OFFICE_OWN_CLASS VARCHAR2(1)  , /* */
    REP_MOBILE VARCHAR2(17)  , /* */
    LICTAX VARCHAR2(1)  , /* */
    HOSCRE VARCHAR2(1)  , /* */
    COM_NUM VARCHAR2(13)  , /* */
    GUBUN VARCHAR2(25)  , /* */
    DOC_CODE VARCHAR2(30)  , /* */
    OFFICE_USE_NAME VARCHAR2(20)  , /* */
    MEMO_CONT VARCHAR2(256)  , /* */
    WRT_ID VARCHAR2(16)  , /* */
    INS_DT VARCHAR2(24)  , /* */
    UPD_DT VARCHAR2(24)  , /* */
    ASSI_TMP_WRT_NUM VARCHAR2(12)  , /* */
    ASSI_COI_WRT_NUM VARCHAR2(6)  , /* */
    ASSI_COMMANA_CLASS VARCHAR2(4)  , /* */
    ASSI_MANA_NUM VARCHAR2(18)  , /* */
    ASSI_STE VARCHAR2(1)  , /* */
    ASSI_NAME VARCHAR2(50)  , /* */
    ASSI_TELNUM VARCHAR2(17)  , /* */
    ASSI_REP VARCHAR2(20)  , /* */
    ASSI_COMNUM VARCHAR2(13)  , /* */
    ASSI_ADDR VARCHAR2(120)  , /* */
    ASSI_POST_NUM VARCHAR2(120)  , /* */
    ASSI_DETAIL_ADDR VARCHAR2(120)  , /* */
    ASSI_GUBUN VARCHAR2(1)  , /* */
    ASSI_WRT_DT VARCHAR2(24)  , /* */
    ASSI_CHGBRE_SEQ VARCHAR2(4)  , /* */
    TRAN_TMP_WRT_NUM VARCHAR2(12)  , /* */
    TRAN_COI_WRT_NUM VARCHAR2(6)  , /* */
    TRAN_COMMANA_CLASS VARCHAR2(4)  , /* */
    TRAN_MANA_NUM VARCHAR2(18)  , /* */
    TRAN_NAME VARCHAR2(50)  , /* */
    TRAN_TELNUM VARCHAR2(17)  , /* */
    TRAN_REP VARCHAR2(20)  , /* */
    TRAN_COMNUM VARCHAR2(13)  , /* */
    TRAN_ADDR VARCHAR2(120)  , /* */
    TRAN_POST_NUM VARCHAR2(6)  , /* */
    TRAN_DETAIL_ADDR VARCHAR2(120)  , /* */
    TRAN_GUBUN VARCHAR2(1)  , /* */
    TRAN_WRT_DT VARCHAR2(24)  , /* */
    TRAN_CHGBRE_SEQ VARCHAR2(4)  , /* */
    COMPANY_DIAG_BAS_DT2 VARCHAR2(4)  , /* */
    BUSS_YMD VARCHAR2(8)  , /* */
    FOREIGN_YN VARCHAR2(1)  , /* */
    REGIST_YMD VARCHAR2(8)  , /* */
    ASSI_BUSS_YMD VARCHAR2(8)  , /* */
    ASSI_FOREIGN_YN VARCHAR2(1)  , /* */
    ASSI_REGIST_YMD VARCHAR2(8)  , /* */
    TRAN_BUSS_YMD VARCHAR2(8)  , /* */
    TRAN_FOREIGN_YN VARCHAR2(1)  , /* */
    TRAN_REGIST_YMD VARCHAR2(8)  , /* */
    PRIMARY KEY(RECV_NUM,SIDO_CODE)
   );
