
SELECT 
	SEQ, TMP_WRT_NUM, RECV_NUM, SIDO_CODE, CAP_PROC, COI_WRT_NUM, ASSE_DT, ASSE_AOM, APPL_TERM_START_DT, CONFIRM, WRT_ID, UPD_DT, INS_DT, APPL_TERM_END_DT, SEQ_LINK_CAPABILITY 
FROM   PT_R_WORK_CAPABILITY_TEMP ;
                   
