
SELECT 
	TMP_WRT_NUM, SIDO_CODE, COMMANA_CLASS, MANA_NUM, NAME, REP_SSN1, REP_SSN2, REP_NM_KOR, REP_NM_HAN, REP_TEL_NUM, ADDR_POST_NUM, ADDR_ADDR, ADDR_DETAIL_ADDR, ADDR_TEL_NUM, ADDR_FAX_NUM, EMAIL_ADDR, OFFICE_AREA, OFFICE_USE_CODE, COMPANY_DIAG_CLASS_CODE, COMPANY_DIAG_BAS_DT, COMPANY_DIAG_ISSUE_DT, DIAG_ORG_CODE, DIAG_NM_NM, DIAG_NM_WRT_NUM, PAY_CAP, REA_CAP, TUP_AOM, TUP_CLASS_CODE, C_COM_DT, C_COM_CAUSE_CODE, COM_COV_DT, WRT_ID, UPD_DT, INS_DT, WRT_DT, BAS_STA_DT, OFFICE_OWN_CLASS, COI_WRT_NUM, REP_MOBILE, LICTAX, HOSCRE, SND_DT, SND_STE, COM_NUM, ADDR_TEL_NUM1, ADDR_TEL_NUM2, ADDR_TEL_NUM3, ADDR_FAX_NUM1, ADDR_FAX_NUM2, ADDR_FAX_NUM3, REP_MOBILE1, REP_MOBILE2, REP_MOBILE3, RECV_NUM, BUSS_YMD, FOREIGN_YN, REGIST_YMD 
FROM   PT_R_TRANS_COMPANY_BEFORE ;
                   
