
SELECT 
	CHGBRE_SEQ, TMP_WRT_NUM, DIAG_ORG_CODE, PAY_CAP, REA_CAP, TUP_AOM, TUP_CLASS_CODE, COMPANY_DIAG_CLASS_CODE, COMPANY_DIAG_BASDT, COMPANY_DIAG_ISSUEDT, DIAG_NM_NM, DIAG_NM_WRT_NUM, WRT_ID, UPD_DT, INS_DT 
FROM   PT_R_COMPANY_DIAGNOSTIC ;
                   
