
create table PT_R_BASIC_STATEMENT(
    RECV_NUM VARCHAR2(12) NOT NULL , /* */
    SIDO_CODE VARCHAR2(4) NOT NULL , /* */
    RECV_DT VARCHAR2(8)  , /* */
    RECV_TIME VARCHAR2(4)  , /* */
    PROC_LIM VARCHAR2(8)  , /* */
    OFFI_PART VARCHAR2(50)  , /* */
    OFFI_PART_REBO_WRT_NUM VARCHAR2(12)  , /* */
    COI_WRT_NUM VARCHAR2(12)  , /* */
    DEFI_STE VARCHAR2(1)  , /* */
    WRT_ID VARCHAR2(16)  , /* */
    UPD_DT VARCHAR2(24)  , /* */
    INS_DT VARCHAR2(24)  , /* */
    NAME VARCHAR2(50)  , /* */
    REP_NM_KOR VARCHAR2(20)  , /* */
    ADDR_ADDR VARCHAR2(200)  , /* */
    WRT_DT VARCHAR2(8)  , /* */
    PROC_TIME VARCHAR2(6)  , /* */
    ADDR_DETAIL_ADDR VARCHAR2(120)  , /* */
    ADDR_POST_NUM VARCHAR2(6)  , /* */
    TMP_WRT_NUM VARCHAR2(12)  , /* */
    CHGBRE_SEQ NUMBER(4)  , /* */
    MEMO_CONT VARCHAR2(256)  , /* */
    COMMANA_CLASS VARCHAR2(1)  , /* */
    MANA_NUM VARCHAR2(18)  , /* */
    REP_SSN1 VARCHAR2(18)  , /* */
    REP_SSN2 VARCHAR2(21)  , /* */
    REP_NM_HAN VARCHAR2(20)  , /* */
    REP_TEL_NUM VARCHAR2(17)  , /* */
    ADDR_TEL_NUM VARCHAR2(17)  , /* */
    ADDR_FAX_NUM VARCHAR2(17)  , /* */
    EMAIL_ADDR VARCHAR2(30)  , /* */
    OFFICE_AREA VARCHAR2(10)  , /* */
    OFFICE_USE_CODE VARCHAR2(6)  , /* */
    COMPANY_DIAG_CLASS_CODE VARCHAR2(6)  , /* */
    COMPANY_DIAG_BAS_DT VARCHAR2(8)  , /* */
    COMPANY_DIAG_ISSUE_DT VARCHAR2(8)  , /* */
    DIAG_NM_NM VARCHAR2(50)  , /* */
    DIAG_NM_WRT_NUM VARCHAR2(50)  , /* */
    DIAG_ORG_CODE VARCHAR2(6)  , /* */
    PAY_CAP VARCHAR2(15)  , /* */
    REA_CAP VARCHAR2(15)  , /* */
    TUP_CLASS_CODE VARCHAR2(6)  , /* */
    TUP_AOM VARCHAR2(15)  , /* */
    C_COM_DT VARCHAR2(8)  , /* */
    C_COM_CAUSE_CODE VARCHAR2(6)  , /* */
    COM_COV_DT VARCHAR2(8)  , /* */
    BAS_STA_DT VARCHAR2(8)  , /* */
    OFFICE_OWN_CLASS VARCHAR2(1)  , /* */
    STA_CHG_CLASS_CODE VARCHAR2(6)  , /* */
    CHG_DT VARCHAR2(8)  , /* */
    MOT_STE VARCHAR2(6)  , /* */
    REP_MOBILE VARCHAR2(17)  , /* */
    HOSCRE VARCHAR2(1)  , /* */
    LICTAX VARCHAR2(1)  , /* */
    SND_DT VARCHAR2(8)  , /* */
    SND_STE VARCHAR2(1)  , /* */
    COM_NUM VARCHAR2(13)  , /* */
    COMPANY_DIAG_BAS_DT2 VARCHAR2(4)  , /* */
    EXT_CHG_CLASS_CODE VARCHAR2(4)  , /* */
    DOC_CODE VARCHAR2(50)  , /* */
    GUBUN VARCHAR2(25)  , /* */
    OFFICE_USE_NAME VARCHAR2(50)  , /* */
    BUSS_YMD VARCHAR2(8)  , /* */
    FOREIGN_YN VARCHAR2(1)  , /* */
    REGIST_YMD VARCHAR2(8)  , /* */
    UNION_INVEST_NUM VARCHAR2(5)  , /* */
    MIDAL_YN VARCHAR2(1)  , /* */
    PRIMARY KEY(RECV_NUM,SIDO_CODE)
   );
