
SELECT 
	SEQ, TMP_WRT_NUM, SI_DO_CODE, SI_GUN_GU_CODE, POS_CLASS, ENT_DT, RET_DT, NM_KOR, NM_HAN, ORI, ADDR, SSN1, SSN2, HEFA, HEFA_RELA, REMARK, CHAR_REF_YN, WRT_ID, INS_DT, UPD_DT, SEND_YN, FOREIGN_YN 
FROM   PT_R_REFFER ;
                   
