
SELECT 
	REC_NUM, SD_CODE, RC_REGIST_NUM, COM_NAME, REC_DATE, WRT_ID, STATE_PERIOD, REGIST_NUM, STATE_ORGAN, OFFICE_TEL, STATE_RECORD_NUM, OFFICE_FAX, UDP_DT, REP_NAME, INS_DT, OFFICE_ADDR 
FROM   PT_R_RE_DELIVERY_STATEMENT ;
                   
