
SELECT 
	RECV_NUM, SIDO_CODE, COI_WRT_NUM, RECV_DT, OFFI_PART, OFFI_PART_REBO_WRT_NUM, NAME, WRT_NUM, REP_NM_KOR, REP_NM_HAN, OFF_ADDR, TEL_NUM, C_COM_DT, WRT_ID, UPD_DT, INS_DT, C_COM_CAUSE, DEFI_STE, ADDR_ADDR, ADDR_POST_NUM, ADDR_DETAIL_ADDR, PROC_LIM, MEMO_CONT, MOT_STE, TMP_WRT_NUM, DOC_CODE 
FROM   PT_R_CLOSE_STATEMENT ;
                   
