
SELECT 
	RECV_NUM, SIDO_CODE, COI_WRT_NUM, MOT_STE, DEFI_STE, RECV_DT, RECV_TIME, PROC_LIM, PROC_TIME, COMMANA_CLASS, MANA_NUM, NAME, REP_SSN1, REP_SSN2, REP_NM_KOR, REP_NM_HAN, REP_TEL_NUM, ADDR_POST_NUM, ADDR_ADDR, ADDR_DETAIL_ADDR, ADDR_TEL_NUM, ADDR_FAX_NUM, EMAIL_ADDR, OFFICE_AREA, OFFICE_USE_CODE, COMPANY_DIAG_CLASS_CODE, COMPANY_DIAG_BAS_DT, COMPANY_DIAG_ISSUE_DT, DIAG_ORG_CODE, DIAG_NM_NM, DIAG_NM_WRT_NUM, PAY_CAP, REA_CAP, TUP_AOM, TUP_CLASS_CODE, COM_COV_DT, BAS_STA_DT, OFFICE_OWN_CLASS, REP_MOBILE, LICTAX, HOSCRE, COM_NUM, GUBUN, DOC_CODE, OFFICE_USE_NAME, MEMO_CONT, WRT_ID, INS_DT, UPD_DT, TMP_WRT_NUM, WRT_DT, CHG_DT, CHGBRE_SEQ, COMPANY_DIAG_BAS_DT2, BUSS_YMD, FOREIGN_YN, REGIST_YMD 
FROM   PT_R_M_UNION_STATEMENT ;
                   
