
SELECT 
	CARE_BOOK_ISSUE_NUM, ENGINEER_SSN1, ENGINEER_SSN2, WRT_NUM, ENGINEER_GRADE, ENGINEER_CLASS, QUAL_ITEM, NM_KOR, NM_HAN, CARE_BOOK_VAL_START_DT, CARE_BOOK_VAL_END_DT, EDU_COMP_DT, POST_NUM, ADDR, DETAIL_ADDR, GROUP_CODE, WRT_ID, UPD_DT, WRT_DT 
FROM   PT_R_ENGINEER_MASTER ;
                   
