
SELECT 
	SEQ, SIDO_NM, SIGUNGU_NM, TEL, OFFPART, AREA_CODE, WRT_ID, INS_DT, UPD_DT, REMARK, HOME, ADDR, SIDO_CAPTAIN, SIDO_FULL_NM, SIDO_NM_CUT, SIGUNGU_NM_CUT, COI_WRT_NUM, NUM2, SIDO_SEQ, SIGUNGU_SEQ 
FROM   PT_SIDO_CODE ;
                   
