
SELECT 
	SIDO_CODE, SIGUNGU_CODE, NEW_WRT, BAS_STA, AFF, ASSI_TRAN, USEBEF_INSP, CYTYSEAL, WRT_ID, INS_DT, UPD_DT, SERVER_ADDR, SERVER_YN, SEND_SYS_ID, RECV_SYS_ID, CITYSEAL_USE_YN, CITYSEAL_WIDTH, CITYSEAL_HEIGHT, GROUPWARE_MODULE_TYPE, ONLINE_CERT_USE_YN, APPL_GUBUN, WEEKCHK, INSTODAY 
FROM   PT_S_SYSVAR_MASTER ;
                   
