
create table PT_UB_EQUIPMENT(
    RECV_NUM VARCHAR2(30) NOT NULL , /* */
    SIDO_CODE VARCHAR2(5) NOT NULL , /* */
    SIGUNGU_CODE VARCHAR2(4) NOT NULL , /* */
    CIV_RECV_NUM VARCHAR2(100)  , /* */
    TYPE_PROC_NO_CA VARCHAR2(50)  , /* */
    TYPE_PROC_NM_CA VARCHAR2(100)  , /* */
    FREQUENCY_SCOPE_CA VARCHAR2(20)  , /* */
    WIRE_TYPE_CA VARCHAR2(100)  , /* */
    TYPE_PROC_NO_MA VARCHAR2(50)  , /* */
    TYPE_PROC_NM_MA VARCHAR2(100)  , /* */
    FREQUENCY_SCOPE_MA VARCHAR2(20)  , /* */
    WIRE_TYPE_MA VARCHAR2(100)  , /* */
    TYPE_PROC_NO_SMA VARCHAR2(50)  , /* */
    TYPE_PROC_NM_SMA VARCHAR2(100)  , /* */
    FREQUENCY_SCOPE_SMA VARCHAR2(20)  , /* */
    WIRE_TYPE_SMA VARCHAR2(100)  , /* */
    INS_DT VARCHAR2(24)  , /* */
    UPD_DT VARCHAR2(24)  , /* */
    PRIMARY KEY(RECV_NUM,SIDO_CODE,SIGUNGU_CODE)
   );
