
CREATE TABLE PT_KICA_TRANS_LOG
(
  SEQ         NUMBER(11)                        NOT NULL,
  U_D_FLAG    CHAR(1 BYTE),
  TABLE_NAME  VARCHAR2(60 BYTE),
  LOG      VARCHAR2(2000 BYTE),
  ERR_YN      CHAR(1 BYTE),
  UPD_DT      VARCHAR2(24 BYTE),
  INS_DT      VARCHAR2(24 BYTE),
  PRIMARY KEY(SEQ)
);



CREATE TABLE TEST_ICS_TB
(
  SEQ           VARCHAR2(20 BYTE),
  FILD1         VARCHAR2(20 BYTE),
  FILD2         VARCHAR2(20 BYTE),
  FILD3         VARCHAR2(20 BYTE),
  KICA_INS_DT   VARCHAR2(24 BYTE),
  ICS_TRANS_DT  VARCHAR2(24 BYTE)
);

CREATE TABLE TEST_KICA_TB
(
  SEQ           VARCHAR2(20 BYTE),
  FILD1         VARCHAR2(20 BYTE),
  FILD2         VARCHAR2(20 BYTE),
  FILD3         VARCHAR2(20 BYTE),
  KICA_INS_DT   VARCHAR2(24 BYTE),
  ICS_TRANS_DT  VARCHAR2(24 BYTE)
);

